# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a53893a6927e6dcf8dbf49ed460c89682e4e836140f4039db4092cec4b0d1ee22f4a1227738f70698db3bc5873c40638ec5239994665a7f52b78a60215823eb

test:
  secret_key_base: 91c76ca2245341427122933564e03b8e5cb35a2dc67c5c79f1d10fb2b6a39a656c025ccb08c3fa180cd8328b57d4632be2ad14e0e5c8e960c2123816c5da3f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
